
DECLARE
  V_RESULT   CHAR;
  V_FAILED   BOOLEAN := FALSE;

  PROCEDURE ASSERT_EQUAL (
    P_TEST_NAME VARCHAR2,
    P_EXPECTED  CHAR,
    P_ACTUAL    CHAR
  ) IS
  BEGIN
    IF P_EXPECTED = P_ACTUAL THEN
      DBMS_OUTPUT.PUT_LINE('OK ' || P_TEST_NAME || ' - PASS');
    ELSE
      DBMS_OUTPUT.PUT_LINE(
        'NOK ' || P_TEST_NAME || ' - FAIL (EXPECTED=' ||
        P_EXPECTED || ', ACTUAL=' || P_ACTUAL || ')'
      );
      V_FAILED := TRUE;
    END IF;
  END;
  
BEGIN
  DBMS_OUTPUT.PUT_LINE ('--------------------------------');
  DBMS_OUTPUT.PUT_LINE ('BEGIN == PKG_VALIDATION TEST == ');
  DBMS_OUTPUT.PUT_LINE ('--------------------------------');
  DBMS_OUTPUT.NEW_LINE;
  
  -- TEST 1: NULL
  V_RESULT := APP_APEX.PKG_VALIDATION.FN_SIZE_VALIDATION(NULL);
  ASSERT_EQUAL('NULL VALUE', 'N', V_RESULT);

  -- TEST 2: EMPTY
  V_RESULT := APP_APEX.PKG_VALIDATION.FN_SIZE_VALIDATION('');
  ASSERT_EQUAL('EMPTY STRING', 'N', V_RESULT);

  -- TEST 3: LENGTH < 3
  V_RESULT := APP_APEX.PKG_VALIDATION.FN_SIZE_VALIDATION('AB');
  ASSERT_EQUAL('LENGTH < 3', 'N', V_RESULT);

  -- TEST 4: LENGTH = 3
  V_RESULT := APP_APEX.PKG_VALIDATION.FN_SIZE_VALIDATION('ABC');
  ASSERT_EQUAL('LENGTH = 3', 'Y', V_RESULT);

  -- TEST 5: LENGTH > 3
  V_RESULT := APP_APEX.PKG_VALIDATION.FN_SIZE_VALIDATION('ABCDE');
  ASSERT_EQUAL('LENGTH > 3', 'Y', V_RESULT);

  -- RESULT
  IF V_FAILED THEN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'NOK TEST RESULT: FAILED');
  ELSE
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'OK TEST RESULT: ALL TESTS PASSED');
  END IF;

  DBMS_OUTPUT.NEW_LINE;
  DBMS_OUTPUT.PUT_LINE ('--------------------------------');
  DBMS_OUTPUT.PUT_LINE ('END   == PKG_VALIDATION TEST == ');
  DBMS_OUTPUT.PUT_LINE ('--------------------------------');
  
END;
/
