CREATE TABLE APP_APEX.PERSON (
    PERSON_ID         NUMBER(10)       NOT NULL,
    FIRST_NAME        VARCHAR2(80)     NOT NULL,
    LAST_NAME         VARCHAR2(80),
    PERSON_FLAG       CHAR(1)          NOT NULL,  -- F = Fisica, J = Juridica
    PERSON_TYPE_ID    NUMBER(10)       NOT NULL,

    CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID),

    CONSTRAINT CK_PERSON_FLAG CHECK (PERSON_FLAG IN ('F','J')),

    CONSTRAINT FK_PERSON_PERSON_TYPE
       FOREIGN KEY (PERSON_TYPE_ID)
       REFERENCES APP_APEX.PERSON_TYPE (PERSON_TYPE_ID)
);

CREATE INDEX IDX_PERSON_TYPE ON APP_APEX.PERSON (PERSON_TYPE_ID);