CREATE TABLE APP_APEX.PERSON_LOG (
    LOG_ID            NUMBER(20)       NOT NULL,
    PERSON_ID         NUMBER(10)       NOT NULL,
    OPERATION         VARCHAR2(10)     NOT NULL,
    OPERATION_DATE    DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_PERSON_LOG PRIMARY KEY (LOG_ID)
);