CREATE TABLE APP_APEX.PERSON_TYPE (
    PERSON_TYPE_ID    NUMBER(10)       NOT NULL,
    TYPE_NAME         VARCHAR2(60)     NOT NULL,

    CONSTRAINT PK_PERSON_TYPE PRIMARY KEY (PERSON_TYPE_ID),
    CONSTRAINT UK_PERSON_TYPE_NAME UNIQUE (TYPE_NAME)
);